---
- name: Set up envionment how I like it
  hosts: localhost

  tasks:

  - name: Download Rust Installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'

  - name: Run Rust Installer
    shell: /tmp/sh.rustup.rs -y

  - name: "Install {{ item }} Rust package"
    community.general.cargo:
      name: "{{ item }}"
    with_items:
      - eza
      - ripgrep
      - bat
      - fd-find
      - git-delta
    community.general.cargo:
      name: git-delta

  - name: fetch fzf from github
    git:
      repo: 'https://github.com/junegunn/fzf.git'
      dest: '{{ ansible_env.HOME }}/fzf'
      version: HEAD # latest

  - name: Run fzf install script
    shell:
      chdir: '{{ ansible_env.HOME }}/fzf'
      cmd: '{{ ansible_env.HOME }}/fzf/install --no-key-bindings --no-completion --no-update-rc'

  - name: Download mise-en-place installer
    get_url:
      url: https://mise.run
      dest: /tmp/mise.run
      mode: '0755'
      force: 'yes'

  - name: Run mise-en-place installer
    shell: /tmp/mise.run

  - name: Download GNU Stow
    get_url:
      url: https://ftp.gnu.org/gnu/stow/stow-2.4.1.tar.gz
      dest: /tmp/stow-2.4.1.tar.gz
      mode: '0755'
      force: 'yes'

  - name: Extract GNU Stow
    unarchive:
      src: /tmp/stow-2.4.1.tar.gz
      dest: /tmp

  - name: Autotools configure GNU Stow
    shell:
      cmd: ./configure
      chdir: /tmp/stow-2.4.1

  - name: Build GNU Stow
    shell:
      cmd: make
      chdir: /tmp/stow-2.4.1

  - name: Install GNU Stow
    shell:
      cmd: make install
      chdir: /tmp/stow-2.4.1
    become: True
