- name: Set up AL2 envionment how I like it
  hosts: localhost

  tasks:

  - name: Install SSM plugin
    yum:
      name: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
      state: present
    become: true
