- name: Set up AL2 envionment how I like it
  hosts: localhost

  tasks:

  - name: Install SSM plugin
    shell: sudo yum install -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
    args:
      creates: /usr/local/sessionmanagerplugin/bin/session-manager-plugin
