---
- name: Set up envionment how I like it
  hosts: localhost

  tasks:

  - name: Download Rust Installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'

  - name: Run Rust Installer
    shell: /tmp/sh.rustup.rs -y

  - name: Install "eza" Rust package
    community.general.cargo:
      name: eza

  - name: Install "ripgrep" Rust package
    community.general.cargo:
      name: ripgrep

  - name: Install "bat" Rust package
    community.general.cargo:
      name: bat

  - name: Install "fd-find" Rust package
    community.general.cargo:
      name: fd-find
