---
- name: Install emacs from source
  hosts: localhost

  tasks:

  - name: Check if emacs is already installed
    command: which emacs
    register: emacs_check
    changed_when: false
    failed_when: false

  - name: Download tree-sitter source
    get_url:
      url: https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.25.6.tar.gz
      dest: /tmp
      mode: '0644'
    when: emacs_check.rc != 0

  - name: Extract tree-sitter source
    unarchive:
      src: /tmp/tree-sitter-0.25.6.tar.gz
      dest: /tmp
    when: emacs_check.rc != 0

  - name: Build tree-sitter
    shell:
      cmd: make -j$(nproc)
      chdir: /tmp/tree-sitter-0.25.6
    when: emacs_check.rc != 0

  - name: Install tree-sitter
    shell:
      cmd: make install
      chdir: /tmp/tree-sitter-0.25.6
    become: true
    when: emacs_check.rc != 0

  - name: Download emacs source
    get_url:
      url: https://ftp.gnu.org/gnu/emacs/emacs-30.1.tar.gz
      dest: /tmp
      mode: '0644'
    when: emacs_check.rc != 0

  - name: Extract emacs source
    unarchive:
      src: /tmp/emacs-30.1.tar.gz
      dest: /tmp
    when: emacs_check.rc != 0

  - name: Autotools configure emacs
    shell:
      cmd: TREE_SITTER_CFLAGS=-I/usr/local/include TREE_SITTER_LIBS="-L/usr/local/lib -ltree-sitter" ./configure --with-native-compilation --with-x-toolkit=no --with-tree-sitter
      chdir: /tmp/emacs-30.1
    when: emacs_check.rc != 0

  - name: Build emacs
    shell:
      cmd: make -j$(nproc)
      chdir: /tmp/emacs-30.1
    when: emacs_check.rc != 0

  - name: Install emacs
    shell:
      cmd: make install
      chdir: /tmp/emacs-30.1
    become: true
    when: emacs_check.rc != 0
