# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# split current window horizontally
bind - split-window -v
# split current window vertically
bind _ split-window -h

# Use Shift-arrow keys without prefix key to switch panes
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

setw -g automatic-rename on # rename window to reflect current program

set -g status-interval 2
set -g status-position bottom

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

set -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'uhs-robert/tmux-oasis'

set-option -g history-limit 10000

# Tmux must be told to use full RGB colors
# https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour
set -as terminal-overrides ",xterm-256color:RGB"

# Set up clipboard
set -g set-clipboard on

# Required to make Clipetty in emacs work better on re-attach by appending
# "SSH_TTY" to "update-environment". See
# https://github.com/spudlyo/clipetty?tab=readme-ov-file#dealing-with-a-stale-ssh_tty-environment-variable
set -ag update-environment "SSH_TTY"

# Enable passthrough mode. Using this so clipetty can pass through OSC 52 clipboard commands
# https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it
set -g allow-passthrough on

# Initialize TMUX plugin manager (must be at bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
